services:
  train:
    build:
      context: ..
      dockerfile: docker/Dockerfile.train
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../logs:/app/logs

  serve:
    build:
      context: ..
      dockerfile: docker/Dockerfile.serve
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
      - ../logs:/app/logs